site_name: GSWA Supermodel
copyright: Copyright &copy; Government of Western Australia (Department of Mines, Industry Regulation and Safety), 2022
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: assets/favicon.png
  palette:
    scheme: youtube
  logo: assets/classes-icon.svg
  # custom_dir: overrides
nav:
    - 'index.md'
    - 'supermodel.md'
    - 'background.md'
    - 'backbone.md'
    - 'components.md'
    - 'vocabularies.md'
    - 'validators.md'