site_name: GSWA Supermodel
copyright: Copyright &copy; Government of Western Australia (Department of Mines, Industry Regulation and Safety), 2022
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - md_in_html
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  name: material
  favicon: assets/favicon.png
  palette:
    scheme: youtube
  logo: assets/classes-icon.svg
  features:
    - navigation.indexes
    - toc.follow
  # custom_dir: overrides
nav:
    - 'index.md'
    - 'background.md'
    - 'backbone.md'
    - 'Component Models':
        - 'components/index.md'
        - 'GeoFeatures Hierarchy': 'components/geofeatures-hierarchy.md'
        - 'Bore': 'components/bore.md'
        - 'Mine': 'components/mine.md'
        - 'Mining Authorisation': 'components/mining-authorisation.md'
        - 'Resource Occurrence': 'components/resource-occurrence.md'
        - 'Geosample': 'components/geosample.md'
    - 'vocabularies.md'
    - 'pids.md'

# SVG resizer: https://svg-converter.com/resize