site_name: GSWA Supermodel
copyright: Copyright &copy; Government of Western Australia (Department of Mines, Industry Regulation and Safety), 2022
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - md_in_html
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  name: material
  favicon: assets/favicon.png
  palette:
    scheme: youtube
  logo: assets/classes-icon.svg
  # custom_dir: overrides
nav:
    - 'index.md'
    - 'supermodel.md'
    - 'background.md'
    - 'backbone.md'
    - 'Component Models':
        - 'Overview': 'components.md'
        - 'Features Hierarchy': 'components/features-hierarchy.md'
        - 'Geological Features': 'components/geo-features.md'
        - 'Sites & Admin Features': 'components/sites-admin.md'
        - 'Bores': 'components/bores.md'
        - 'Mines': 'components/mines.md'
        - 'Resource Occurence': 'components/resource-occurrence.md'
        - 'Samples': 'components/samples.md'
        - 'Authorities': 'components/authorities.md'
    - 'vocabularies.md'
    - 'validators.md'

# SVG resizer: https://svg-converter.com/resize